name: Netology-ci

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare system
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements.txt

      - name: Install postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'

#      - name: Create User
#        run: ...
#
#      - name: Create DB
#        run: ...



#      - name: Run migrations
#        run: python manage.py migrate

#      - name: Linting
#        run: flake8 .

#      - name: Testing
#        run: python manage.py test
#        env:
#          DB_NAME: test
#          DB_HOST: localhost
#          DB_PORT: 5432